# This playbook executes /tmp/leoshscript.sh on multiple hosts for different webinstances 
# In the below example you can asign webserver for specific hosts under "content: |" 
# In this case we have 2 hosts ivwb2874 and ivwb2990
# Add your email adress on line "53" .You will recive and email contating log output from each server.
# Always test frist on a single server or two.
#
# Example commands 
# ansible-playbook --syntax-check WebDeletion.yml -i hosts.txt
# ansible-playbook -vv WebDeletionTest.yml -i hosts.txt
#
# Good luck and have fun!
---
- hosts: all
  strategy: free
  remote_user: roothp
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Distribute Packages to hosts
    copy:
      src: /tmp/leoshscript.sh
      dest: /tmp
      mode: 0777

  - name: Creating a file with content for host EXAMPLE1
    copy:
      dest: "/tmp/web66.txt"
      content: |
        web3108
        web3
        web4
      mode: 0666
    delegate_to: EXAMPLE1

  - name: Creating a file with content for host EXAMPLE2
    copy:
      dest: "/tmp/web66.txt"
      content: |
        web4445
        web4232
      mode: 0666
    delegate_to: EXAMPLE2

  - name: Execute script on remote host
    shell: "cd /tmp; /bin/bash leoshscript.sh > {{ inventory_hostname }}.RemovedWebs.txt; chmod 666 {{ inventory_hostname }}.RemovedWebs.txt"

  - name: Copy local file to remotecockpit
    fetch:
      src: /tmp/{{ inventory_hostname }}.RemovedWebs.txt
      dest: /tmp/
      flat: yes
      mode: 0777

  - name: Send Report
    remote_user: ansible
    become: no
    mail:
      subject: "Removed Web Report for host {{ inventory_hostname }} "
      to: EXAMPLE@mail.com
      body: Enjoy RemovedWebs Report
      attach:
        - /tmp/{{ inventory_hostname }}.RemovedWebs.txt
    delegate_to: 127.0.0.1
